[package]
name = "meacode-estudio"
version = "0.1.0"
edition = "2021"
description = "MeaCode Estudio"
authors = ["MeaCode"]

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "1.5", features = ["path-all", "dialog-open", "dialog-save", "fs-all", "shell-open"] }
sysinfo = "0.30"
num_cpus = "1.16"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
