[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]  # Usar lld linker (más rápido)

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/OPT:REF", "-C", "link-arg=/OPT:ICF"]

[net]
retry = 2
git-fetch-with-cli = true

